"""Migration

Revision ID: 0867a18d580f
Revises: 1a660c242acb
Create Date: 2024-03-07 13:53:43.211910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0867a18d580f'
down_revision = '1a660c242acb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
